version: 2

sources:
  - name: jaffle_shop
    database: RAW
    schema: JAFFLE_SHOP
    tables:
      - name: customers
      - name: orders
        config:
          freshness:
            warn_after: 
              {
                count: 24
               ,period: hour
               }
            error_after: 
              {
                count: 48
               ,period: hour
              }
  - name: stripe
    database: RAW
    schema: STRIPE
    tables:
      - name: payments

models:
  - name: stg_jaffle_shop_customers
  - name: stg_jaffle_shop_orders
