version: 2

sources:
  - name: jaffle_shop
    database: ANALYTICS
    schema: JAFFLE_SHOP
    tables:
      - name: customers
      - name: orders


models:
  - name: stg_jaffle_shop_customers
  - name: stg_jaffle_shop_orders
